// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AvroDemo.Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class User : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"User\",\"namespace\":\"AvroDemo.Models\",\"fields\":[{\"name\":\"N" +
				"ame\",\"type\":\"string\"},{\"name\":\"FavoriteNumber\",\"type\":[\"int\",\"null\"]},{\"name\":\"F" +
				"avoriteColor\",\"type\":[\"string\",\"null\"]}]}");
		private string _Name;
		private System.Nullable<System.Int32> _FavoriteNumber;
		private string _FavoriteColor;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return User._SCHEMA;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public System.Nullable<System.Int32> FavoriteNumber
		{
			get
			{
				return this._FavoriteNumber;
			}
			set
			{
				this._FavoriteNumber = value;
			}
		}
		public string FavoriteColor
		{
			get
			{
				return this._FavoriteColor;
			}
			set
			{
				this._FavoriteColor = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Name;
			case 1: return this.FavoriteNumber;
			case 2: return this.FavoriteColor;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Name = (System.String)fieldValue; break;
			case 1: this.FavoriteNumber = (System.Nullable<System.Int32>)fieldValue; break;
			case 2: this.FavoriteColor = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
